# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RoznicaWysokosciOrazPolePowierzchni
                                 A QGIS plugin
 To jest wtyczka obliczająca różnicę wysokości między dwoma punktami oraz pole powierzchni między trzema punktami
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-06-10
        copyright            : (C) 2023 by Aleksandra Krogulska, Maciej Wiśniewski
        email                : maciek.wis12@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load RoznicaWysokosciOrazPolePowierzchni class from file RoznicaWysokosciOrazPolePowierzchni.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .roznica_wysokosci_oraz_pole_powierzchni import RoznicaWysokosciOrazPolePowierzchni
    return RoznicaWysokosciOrazPolePowierzchni(iface)
